version: "3.7"

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    env_file:
      - .env

  backend:
    build: ./backend
    volumes:
      - ./backend/:/code/
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- ./entrypoint.sh
    environment:
      - SQL_HOST=db
    env_file:
      - .env

  worker:
    build: ./backend
    volumes:
      - ./backend/:/code/
    depends_on:
      - backend
    command: ./wait-for-it.sh db:5432 -- ./entrypoint-worker.sh
    environment:
      - SQL_HOST=db
    env_file:
      - .env


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
