# Generated by Django 3.0.6 on 2020-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='name',
        ),
    ]
